uploads = []
generated = []

[[outputs]]
id = "OQ7_k1fz7f00IkEbzBzPB"
uri = "file://efootball-league.tar.gz"
type = "unspecified"
title = "eFootball League — Project Source"

[[outputs]]
id = "XKzZiwDqajHvW3Sz5KbtY"
uri = "file://efootball-league-full.tar.gz"
type = "unspecified"
title = "eFootball League — Updated Build"
